In [1]:
import numpy as np

In [123]:
points2d = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6]])

In [124]:
points3d = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

In [125]:
points3d_idxs = np.array([0, 0, 1])

In [126]:
camera_idxs = np.array([0, 1, 2])

In [127]:
P = np.arange(72).reshape((6, 3, 4))

In [128]:
selected_points3d = points3d[points3d_idxs]

In [129]:
print(selected_points3d)

[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [130]:
print(P)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]]


In [131]:
homo_3d_points = np.concatenate((selected_points3d, np.ones((selected_points3d.shape[0], 1))), axis=1)
homo_3d_points_T = np.transpose(homo_3d_points)

In [132]:
homo_3d_points_T

array([[1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 1., 1.]])

In [133]:
calculated_points2d = np.matmul(P, homo_3d_points_T)
print(calculated_points2d)

[[[  6.   6.   9.]
  [ 22.  22.  37.]
  [ 38.  38.  65.]]

 [[ 54.  54.  93.]
  [ 70.  70. 121.]
  [ 86.  86. 149.]]

 [[102. 102. 177.]
  [118. 118. 205.]
  [134. 134. 233.]]

 [[150. 150. 261.]
  [166. 166. 289.]
  [182. 182. 317.]]

 [[198. 198. 345.]
  [214. 214. 373.]
  [230. 230. 401.]]

 [[246. 246. 429.]
  [262. 262. 457.]
  [278. 278. 485.]]]


In [121]:
calculated_points2d = calculated_points2d[camera_idxs, :, points3d_idxs]
print(calculated_points2d)
print(calculated_points2d.shape)
calculated_points2d /= calculated_points2d[:, -1].reshape((calculated_points2d.shape[0], 1))
calculated_points2d = calculated_points2d[:, :-1]

[[  6.  22.  38.]
 [ 54.  70.  86.]
 [102. 118. 134.]
 [  6.  22.  38.]
 [ 93. 121. 149.]
 [177. 205. 233.]]
(6, 3)


In [122]:
print(calculated_points2d)

[[0.15789474 0.57894737]
 [0.62790698 0.81395349]
 [0.76119403 0.88059701]
 [0.15789474 0.57894737]
 [0.62416107 0.81208054]
 [0.75965665 0.87982833]]


In [94]:
i = 3
print("calculated_points2d=", calculated_points2d[i])
print("camera_idxs[0]=", camera_idxs[i])
print("camera =", P[camera_idxs[i]])
print("points3d[0]=", points3d[points3d_idxs[i]])

print("point2d=", points2d[i])

calculated_points2d= [0.15789474 0.57894737]
camera_idxs[0]= 0
camera = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
points3d[0]= [2 2 2]
point2d= [4 4]


In [160]:
a = np.arange(1200).reshape((100, 3, 4))

In [161]:
b = np.arange(400).reshape((4, 100))

In [162]:
np.einsum('ijk,ki->ij',a,b)

array([[   1400,    3800,    6200],
       [   8654,   11070,   13486],
       [  16004,   18436,   20868],
       [  23450,   25898,   28346],
       [  30992,   33456,   35920],
       [  38630,   41110,   43590],
       [  46364,   48860,   51356],
       [  54194,   56706,   59218],
       [  62120,   64648,   67176],
       [  70142,   72686,   75230],
       [  78260,   80820,   83380],
       [  86474,   89050,   91626],
       [  94784,   97376,   99968],
       [ 103190,  105798,  108406],
       [ 111692,  114316,  116940],
       [ 120290,  122930,  125570],
       [ 128984,  131640,  134296],
       [ 137774,  140446,  143118],
       [ 146660,  149348,  152036],
       [ 155642,  158346,  161050],
       [ 164720,  167440,  170160],
       [ 173894,  176630,  179366],
       [ 183164,  185916,  188668],
       [ 192530,  195298,  198066],
       [ 201992,  204776,  207560],
       [ 211550,  214350,  217150],
       [ 221204,  224020,  226836],
       [ 230954,  233786,  2

In [155]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [156]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])